media: src/content/media
content:
  - name: portfolio
    label: Portfolio
    path: src/content/portfolio
    type: collection
    fields:
      - name: title
        label: Title
        description: The title of the portfolio item
        type: text
      - name: description
        label: Description
        description: The description of the portfolio item
        type: rich-text
      - name: body
        label: Body
        description: The body of the portfolio item
        type: rich-text
      - name: image
        label: Image
        description: The image of the portfolio item
        type: object
        fields:
          - name: url
            label: Source
            description: The source of the image
            type: image
            options:
              input: src/content/media
              output: ../media
              path: src/content/media
          - name: alt
            label: Alt
            description: The alt text of the image
            type: text
      - name: link
        label: Link
        description: The link where the portfolio item can be found
        type: text
      - name: screenshots
        label: Screenshots
        description: The screenshots of the portfolio item
        type: object
        list: true
        fields:
          - name: url
            label: Source
            description: The source of the screenshot
            type: image
            options:
              input: src/content/media
              output: ../media
              path: src/content/media
          - name: alt
            label: Alt
            description: The alt text of the screenshot
            type: text
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    view: 
      fields: [title, description, id, pubDate]
      primary: id
      sort: [pubDate]
    filename: '{primary}.md'
    fields:
      - name: id
        label: id
        description: The ID of the blog post
        type: text
        required: true
        unique: true
      - name: title
        label: Title
        description: The title of the blog post
        type: text
      - name: description
        label: Description
        description: The description of the blog post
        type: rich-text
      - name: body
        label: Body
        description: The body of the blog post
        type: rich-text
      - name: coverimage
        label: Cover Image
        description: The cover image of the blog post
        type: image
        options:
          input: src/content/media
          output: ../media
          path: src/content/media
      - name: pubDate
        label: Publication Date
        description: The date the blog post was published
        type: date       
  # - name: about
  #   label: About
  #   path: src/content/about/about.md
  #   type: file
  #   fields:
  #     - name: title
  #       label: Title
  #       description: The title of the about page
  #       type: text
  #     - name: body
  #       label: Body
  #       description: The body of the about page
  #       type: rich-text
  #     - name: skills
  #       label: Skills
  #       description: The skills of the about page
  #       type: text
  #       list: true
  #       fields:
  #         - name: skill
  #           label: Skill
  #           description: The skill of the about page
  #           type: text
  #     - name: Education
  #       label: Education
  #       description: The education of the about page
  #       type: rich-text
  # - name: config
  #   label: Config
  #   path: src/config.json
  #   type: file
  #   format: json
  #   fields:
  #     - name: title
  #       label: Title
  #       description: The title of the site
  #       type: text
  #     - name: email
  #       label: Email
  #       description: The email of the site
  #       type: text
  #     - name: linkedin
  #       label: LinkedIn
  #       description: The LinkedIn of the site
  #       type: text
  #     - name: cv
  #       label: CV
  #       description: The CV of the site
  #       type: image
  #       options:
  #         input: public/content
  #         output: /content
  #         path: public/content
  #         categories: document
  #     - name: icon
  #       label: Icon
  #       description: The icon of the site
  #       type: image
  #       options:
  #         input: public/content
  #         output: /content
  #         path: public/content
